# Generated by Django 2.0.5 on 2018-06-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180606_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_phone_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Passenger'),
        ),
    ]
