# Generated by Django 2.0.5 on 2018-06-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180608_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='train_id',
        ),
        migrations.AddField(
            model_name='seat',
            name='run_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Run'),
        ),
    ]
