# Generated by Django 2.0.5 on 2018-06-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180609_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='run_id',
        ),
        migrations.AddField(
            model_name='seat',
            name='train_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Train'),
        ),
    ]
