# Generated by Django 2.0.5 on 2018-06-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20180610_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
    ]
